week3/config/routes.rb
Rails.application.routes.draw do

	root 'dashboards#index'

	resources :dashboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

end

week3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week3/app/models/dashboard.rb
class Dashboard < ApplicationRecord

	validates:name, :presence => true,:uniqueness=>true
end

week3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

week3/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def index
		@Dashboard ="halo"

	end

	def show
	end

	def new
		@Dashboard = Dashboard.new
	end

	def create
		
		data=Dashboard.new
		data.name = params[:dashboard][:name]
		data.save
		redirect_to dashboards_path
	end

	def edit
	end

	def update
	end

	def destroy
	end






end

week3/app/helpers/application_helper.rb
module ApplicationHelper
end

week3/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

week3/app/views/dashboards/index.html.erb
<html>

	ini halaman index

	<%=link_to "new", new_dashboard_path%>

</html>

week3/app/views/dashboards/new.html.erb
<html>
	<%= form_for(@Dashboard) do |f| %>
	<div class='form-group'>
		<label class='control-label'> Name </label>
		<%= f.text_field:name, :class => "form control", required:true %>
		</div>

		<hr>

		<div class='form-action pull-right' style='margin-bottom: 0'>
		<%= link_to dashboards_path,style:"margin-right:15px;" do%> Cancel <%end%>
		<%= f.submit class:'btn btn-success',data:{disable_with:"please wait...." }%>
		</div>
		<%end%>
</html>

week3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Week3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>